
USE KARATA

SELECT * FROM PERSONS

SELECT * FROM  MANAGERS_DATA

SELECT * FROM ISTRUCTORS_DATA 

SELECT * FROM MEMBERS_DATA


SELECT * FROM MEMBERSHIPMANAGEMENT


SELECT * FROM ISTRUCTORSHIPMANAGEMENT


INSERT INTO ISTRUCTORSHIPMANAGEMENT
VALUES
	('2023/10/12',1,1,6)


CREATE VIEW ISTRUCTORSHIPMANAGEMENTD AS 
SELECT ISTRUCTORSHIPMANAGEMENT.MANAGEMENTID ,MANAGEMENTDATE , ISTRUCTORSHIPMANAGEMENT.ID , MANAGERS_DATA.FIRSTNAME ,MANAGERS_DATA.LASTNAME ,FULLNAME = ISTRUCTORS_DATA.FIRSTNAME + ' ' +  
ISTRUCTORS_DATA.LASTNAME FROM MANAGERS_DATA RIGHT JOIN ISTRUCTORSHIPMANAGEMENT ON ISTRUCTORSHIPMANAGEMENT.MANAGERID = MANAGERS_DATA.ID
LEFT JOIN ISTRUCTORS_DATA ON ISTRUCTORS_DATA.ID = ISTRUCTORSHIPMANAGEMENT.ISTRUCTORID

SELECT * FROM ISTRUCTORSHIPMANAGEMENTD
